### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kevaldonga** [RAprogramm/neovim-IDE#5]
How do I install this manually as install script is broken at the moment.

**Comment by RAprogramm** [comment]
You have to:
1. Download it.
2. Put repo folder to `$HOME/.config` path with name `nvim` (if you already have `nvim` dir in your `.config`, you should to rename your present `nvim` dir (`nvim_old` for example)).
3. Make sure that you have neovim nightly version and all needed dependensies.
4. Run nvim.
5. Update lazy (inside neovim `:Lazy update` command).

---

You can find dependencies [here](https://github.com/RAprogramm/NEVIRAIDE?tab=readme-ov-file#dependencies)
you can install it by
```sh
yay -S git nonicons ripgrep fd unzip wget curl gzip tar curl npm
```

are you using:
1. Arch linux
2. Kitty terminal
3. Nerd Fonts
???

**Comment by kevaldonga** [comment]
Getting this error `Error detected while processing /home/keval/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/keval/.config/nvim/lua/neviraide/utils/init.lua:34: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/keval/.config/nvim/lua/neviraide/utils/init.lua:34: in main chunk
        [C]: in function 'require'
        /home/keval/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue`

**Comment by kevaldonga** [comment]
yes it is installed. what are the key bindings pre-configured cause I want to edit those, and what other plugins it comes with like treesitter and other file searching plugins ?

**Comment by RAprogramm** [comment]
Inside `$HOME/.config/nvim` directory you have to go to `lua` folder and there are:
1. `NEVERAIDE.lua` file with some settings.
2. `neviraide/lazy` folder contains all installed plugins by categories
├── debug.lua
├── dependencies.lua
├── editor.lua
├── git.lua
├── init.lua
├── lsp.lua
├── treesitter.lua
├── ui.lua
└── utils.lua
Inside of this files you can find installed plugins via lazy.nvim.
3. Configurations and options of all plugins located in `plugins` directory.
4. Keybindings located in `plugins/which-key` directory. Also sorted by categories.

---

By default "leader" key is `<SPACE>`. So to show active keybindings you can press `<SPACE>` and you will see WhichKey floating window.

P.S.: i tried to make keybindings, according to the principle, "I think - I press"...
for example:
1. Lsp Hover - `<SPACE>lh`.
2. Buffers Delete Current = `<SPACE>bdc`
3. Utils Notes Add TODO = `<SPACE>unat`
4. ..... and so on

everyone is accustomed to using such key combinations as are provided by the manufacturer or author of the code editor, for example:
1. in jetbrains LSP hover is `<SHIFT>k` - but you can press it only if you know that...not intuitive i think.
2. in visual studio code terminal is `<CTRL><SHIFT>`` .....
3. in VScode also diagnostic, as i remember, id `<F8>` ....

-----

as for NEVIRAIDE defaults:
terminal have 3 variant:
1. Horizontal `<ALT>+h`
2. Vertical `<ALT>+v`
3. Float `<ALT>+f`

also diagnostic:
1. Diagnostic Line (current) - `<SPACE>dl`
2. Diagnostic Debug Brakepoint - `<SPACE>ddb`
3. and so on
